name: Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Update on methanium
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWD }}
          port: ${{ secrets.SSH_PORT }}
          script: cd /home/${{ secrets.SSH_USER }}/Docs && git pull && bun install && bun run build
